### ISSUE TITLE
[Angular 12] Error:the target entry-point "@dashjoin/json-schema-frm" has missing dependencies: - jsonata

### ISSUE THREAD

**Issue by KostaD02** [dashjoin/json-schema-form#114]
Error: The target entry-point "@dashjoin/json-schema-form" has missing dependencies:
 - jsonata

    at TargetedEntryPointFinder.findEntryPoints (C:\Users\kdaut\OneDrive\Desktop\85\test\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40:23)
    at C:\Users\kdaut\OneDrive\Desktop\85\test\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:29:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (C:\Users\kdaut\OneDrive\Desktop\85\test\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:28:29)       
    at C:\Users\kdaut\OneDrive\Desktop\85\test\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
    at SyncLocker.lock (C:\Users\kdaut\OneDrive\Desktop\85\test\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (C:\Users\kdaut\OneDrive\Desktop\85\test\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)
    at Object.mainNgcc (C:\Users\kdaut\OneDrive\Desktop\85\test\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
    at Object.process (C:\Users\kdaut\OneDrive\Desktop\85\test\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
    at NgccProcessor.processModule (C:\Users\kdaut\OneDrive\Desktop\85\test\node_modules\@ngtools\webpack\src\ngcc_processor.js:175:16)
    at C:\Users\kdaut\OneDrive\Desktop\85\test\node_modules\@ngtools\webpack\src\ivy\host.js:146:18

Does anyone know solution ?

**Comment by aeberhart** [comment]
We list jsonata as a peerDependency:
https://github.com/dashjoin/json-schema-form/blob/master/projects/dashjoin/json-schema-form/package.json

Depending on the package manager, you might still need to list it in your package.json. We do this in the sample app here:
https://github.com/dashjoin/json-schema-form/blob/master/package.json

Please let us know if this helps.

**Comment by KostaD02** [comment]
Added list and peerDependency but still same error

**Comment by aeberhart** [comment]
can you post your package.json?

**Comment by KostaD02** [comment]
after lunch again and adding peerDependency in new project it' worked
